version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-data:/prometheus
      - ./prometheus_services:/etc/prometheus/file_sd:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      
    ports:
      - "9090:9090"     # Prometheus UI/API

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"     # Loki HTTP API
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml:ro
      - ./loki-data:/tmp/loki/
    command:
      - -config.file=/etc/loki/config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"     # Grafana UI

# volumes:
#   prometheus-data:
#   loki-data:
#   grafana-storage:
