global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dynamic_services'
    file_sd_configs:
      - files:
          - '/etc/prometheus/file_sd/*.json'
    metrics_path: '/metrics'
    scheme: http

